/* font.c — vector text with smooth scaling, loaded from a .vtf file
 *
 * The font is NOT compiled into the lib: it's loaded at runtime from a .vtf
 * (vector-type-font) file generated by fonts/type_fixed.py. wpx_font_load()
 * parses it and returns an opaque WPX_Font pointer, used by wpx_text_font().
 *
 * winpixel rasterizes on the CPU and has no blending. Drawing the vector
 * glyph (hundreds of triangles) is expensive for a lot of text; so each
 * glyph is rasterized ONCE into a coverage bitmap (1 byte/pixel: 0/1) at
 * the current scale, and at render time becomes a cheap tinted blit (color
 * per call). The cache is only rebaked when the scale changes -> keeps the
 * scaling smooth.
 *
 * .vtf format (little-endian):
 *   char  magic[4] = "VTF1"
 *   int32 first, last, vert_floats, index_count, glyph_count
 *   float verts[vert_floats]            (x,y interleaved; Y is down)
 *   int32 indices[index_count]
 *   glyph[glyph_count]: int32 voff,vcount,ioff,icount; float advance
 */

#include "winpixel_internal.h"
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define WPX_FONT_MAX_TEXT 1024

/* A single glyph's metadata, as it comes from the file. */
typedef struct {
	int   voff, vcount, ioff, icount;
	float advance;
} vtf_glyph;

/* A baked glyph: coverage bitmap at the current scale. */
typedef struct {
	unsigned char *cov;     /* w*h coverage (0/1); NULL if the glyph is empty */
	int   w, h;             /* bitmap dimensions in pixels                    */
	int   ox, oy;           /* top-left corner relative to (pen,baseline)     */
	float advance;          /* horizontal advance in pixels                   */
} baked_glyph;

/* Cache baked at a single scale. How many different scale calls (title,
   pin, etc.) can coexist in the same frame without rebaking, without the
   caller needing to know about it. */
#define WPX_FONT_CACHE_SLOTS 4

typedef struct {
	baked_glyph *baked;   /* count entries; NULL if the slot was never used */
	float        scale;
	int          ready;
	unsigned     lru;     /* higher = more recently used */
} wpx_font_slot;

/* Opaque font handle: loaded geometry + coverage cache (N scales). */
struct WPX_Font {
	int        first, last, count;
	float     *verts;   int vert_floats;
	int32_t   *indices; int index_count;
	vtf_glyph *glyphs;              /* count entries */

	wpx_font_slot slots[WPX_FONT_CACHE_SLOTS]; /* per-scale LRU cache */
	unsigned      lru_clock;
};

/* Rasterizer: fills a triangle (coords in pixels) into the coverage buffer,
   marking 1. Barycentric test, hard edges (winpixel has no blending), works
   with any winding order. Samples at the pixel center. */
static void font_raster_triangle (unsigned char *cov, int w, int h,
                                   float ax, float ay, float bx, float by, float cx, float cy) {

	int lox = (int)floorf(fminf(ax, fminf(bx, cx)));
	int loy = (int)floorf(fminf(ay, fminf(by, cy)));
	int hix = (int)ceilf (fmaxf(ax, fmaxf(bx, cx)));
	int hiy = (int)ceilf (fmaxf(ay, fmaxf(by, cy)));
	if (lox < 0) lox = 0;
	if (loy < 0) loy = 0;
	if (hix > w) hix = w;
	if (hiy > h) hiy = h;

	for (int y = loy; y < hiy; ++y) {
		float py = y + 0.5f;
		for (int x = lox; x < hix; ++x) {
			float px = x + 0.5f;
			float e0 = (bx - px) * (cy - py) - (by - py) * (cx - px);
			float e1 = (cx - px) * (ay - py) - (cy - py) * (ax - px);
			float e2 = (ax - px) * (by - py) - (ay - py) * (bx - px);
			if ((e0 >= 0.0f && e1 >= 0.0f && e2 >= 0.0f) ||
			    (e0 <= 0.0f && e1 <= 0.0f && e2 <= 0.0f))
				cov[y * w + x] = 1;
		}
	}
}

/* Blits the coverage in color 'color', straight into the framebuffer (no
   blending: writes the color wherever cov==1). dx,dy = top-left corner in
   the framebuffer. */
static void font_blit_cov (const unsigned char *cov, int w, int h, int dx, int dy, Color32 color) {

	uint32_t *fb = wpx_render.buffer_screen;
	int fw = wpx_render.w, fh = wpx_render.h;
	uint32_t c = wpx_color_to_pixel(color);
	if (!fb) return;

	for (int y = 0; y < h; ++y) {
		int sy = dy + y;
		if (sy < 0 || sy >= fh) continue;
		for (int x = 0; x < w; ++x) {
			if (!cov[y * w + x]) continue;
			int sx = dx + x;
			if (sx < 0 || sx >= fw) continue;
			fb[sy * fw + sx] = c;
		}
	}
}

/* Bakes a glyph: rasterizes its geometry into a coverage bitmap. */
static void bake_glyph (const WPX_Font *fp, int gi, float scale, baked_glyph *out) {

	vtf_glyph g = fp->glyphs[gi];
	out->cov = NULL; out->w = out->h = 0; out->ox = out->oy = 0;
	out->advance = g.advance * scale;
	if (g.icount <= 0 || g.vcount <= 0) return;

	/* ink bbox in font units */
	float minx = 1e9f, miny = 1e9f, maxx = -1e9f, maxy = -1e9f;
	for (int i = 0; i < g.vcount; ++i) {
		float vx = fp->verts[(g.voff + i) * 2 + 0];
		float vy = fp->verts[(g.voff + i) * 2 + 1];
		if (vx < minx) minx = vx;
		if (vx > maxx) maxx = vx;
		if (vy < miny) miny = vy;
		if (vy > maxy) maxy = vy;
	}

	int w = (int)ceilf((maxx - minx) * scale) + 1;
	int h = (int)ceilf((maxy - miny) * scale) + 1;
	if (w <= 0 || h <= 0) return;

	unsigned char *cov = (unsigned char *)calloc((size_t)w * h, 1);
	if (!cov) return;

	for (int i = 0; i < g.icount; i += 3) {
		int a = fp->indices[g.ioff + i + 0];
		int b = fp->indices[g.ioff + i + 1];
		int d = fp->indices[g.ioff + i + 2];
		font_raster_triangle(cov, w, h,
			(fp->verts[a*2] - minx) * scale, (fp->verts[a*2+1] - miny) * scale,
			(fp->verts[b*2] - minx) * scale, (fp->verts[b*2+1] - miny) * scale,
			(fp->verts[d*2] - minx) * scale, (fp->verts[d*2+1] - miny) * scale);
	}

	out->cov = cov; out->w = w; out->h = h;
	out->ox  = (int)lroundf(minx * scale);   /* offset from the pen                */
	out->oy  = (int)lroundf(miny * scale);   /* from the baseline (miny<0=top)     */
}

/* Ensures a cache baked at the requested scale and returns its glyphs (count
   entries). Keeps up to WPX_FONT_CACHE_SLOTS scales baked at the same time
   (LRU), so callers that alternate between a few fixed scales per frame
   (e.g. title vs. pin label) don't rebake the whole font on every call —
   it only rebakes for real when the zoom changes, or when more scales are
   requested at once than there are slots. */
static baked_glyph *wpx_font_ensure (WPX_Font *fp, float scale) {

	for (int i = 0; i < WPX_FONT_CACHE_SLOTS; ++i)
		if (fp->slots[i].ready && fp->slots[i].scale == scale) {
			fp->slots[i].lru = ++fp->lru_clock;
			return fp->slots[i].baked;
		}

	/* Pick the least-recently-used slot (or an empty one, which always
	   loses since !ready short-circuits the comparison). */
	int victim = 0;
	for (int i = 1; i < WPX_FONT_CACHE_SLOTS; ++i)
		if (!fp->slots[i].ready || fp->slots[i].lru < fp->slots[victim].lru)
			victim = i;

	wpx_font_slot *s = &fp->slots[victim];
	if (!s->baked) s->baked = (baked_glyph *)calloc((size_t)fp->count, sizeof(baked_glyph));
	if (!s->baked) return NULL;
	for (int i = 0; i < fp->count; ++i) { free(s->baked[i].cov); s->baked[i].cov = NULL; }
	for (int i = 0; i < fp->count; ++i) bake_glyph(fp, i, scale, &s->baked[i]);
	s->scale = scale;
	s->ready = 1;
	s->lru   = ++fp->lru_clock;
	return s->baked;
}

/* Draws already-baked text from the TOP-LEFT corner (x,y). */
static void wpx_font_draw_topleft (WPX_Font *fp, const baked_glyph *baked, Color32 color, float x, float y, const char *buf) {

	/* top of the ink = smallest oy among the characters (<=0) */
	int top = 0, have = 0;
	for (const unsigned char *p = (const unsigned char *)buf; *p; ++p) {
		int c = *p;
		if (c < fp->first || c > fp->last) continue;
		const baked_glyph *bg = &baked[c - fp->first];
		if (!bg->cov) continue;
		if (!have || bg->oy < top) { top = bg->oy; have = 1; }
	}

	int   baseline = (int)lroundf(y) - top;
	float pen = x;
	for (const unsigned char *p = (const unsigned char *)buf; *p; ++p) {
		int c = *p;
		if (c < fp->first || c > fp->last) continue;
		const baked_glyph *bg = &baked[c - fp->first];
		if (bg->cov)
			font_blit_cov(bg->cov, bg->w, bg->h,
			              (int)lroundf(pen) + bg->ox, baseline + bg->oy, color);
		pen += bg->advance;
	}
}

/* ---- Public API ---- */

/* Loads a .vtf font. Returns NULL on error (invalid file/format). */
WINPIXELDLL WPX_Font *WINPIXELCALL wpx_font_load (const char *path) {

	FILE *f = fopen(path, "rb");
	if (!f) return NULL;

	char magic[4];
	int32_t hdr[5];
	if (fread(magic, 1, 4, f) != 4 || memcmp(magic, "VTF1", 4) != 0 ||
	    fread(hdr, sizeof(int32_t), 5, f) != 5) {
		fclose(f);
		return NULL;
	}

	int first = hdr[0], last = hdr[1], vf = hdr[2], ic = hdr[3], gc = hdr[4];
	if (first < 0 || last < first || vf < 0 || ic < 0 || gc != last - first + 1) {
		fclose(f);
		return NULL;
	}

	WPX_Font *fp = (WPX_Font *)calloc(1, sizeof(WPX_Font));
	if (!fp) { fclose(f); return NULL; }

	fp->first = first; fp->last = last; fp->count = gc;
	fp->vert_floats = vf; fp->index_count = ic;
	fp->verts   = (float *)malloc((size_t)vf * sizeof(float));
	fp->indices = (int32_t *)malloc((size_t)ic * sizeof(int32_t));
	fp->glyphs  = (vtf_glyph *)malloc((size_t)gc * sizeof(vtf_glyph));

	int ok = fp->verts && fp->indices && fp->glyphs
	      && fread(fp->verts,   sizeof(float),   vf, f) == (size_t)vf
	      && fread(fp->indices, sizeof(int32_t), ic, f) == (size_t)ic;

	for (int i = 0; ok && i < gc; ++i) {
		int32_t rec[4];
		float   adv;
		ok = fread(rec, sizeof(int32_t), 4, f) == 4 && fread(&adv, sizeof(float), 1, f) == 1;
		if (ok) {
			fp->glyphs[i].voff   = rec[0];
			fp->glyphs[i].vcount = rec[1];
			fp->glyphs[i].ioff   = rec[2];
			fp->glyphs[i].icount = rec[3];
			fp->glyphs[i].advance = adv;
		}
	}

	fclose(f);
	if (!ok) { wpx_font_free(fp); return NULL; }
	return fp;
}

/* Frees the font and its cache. */
WINPIXELDLL void WINPIXELCALL wpx_font_free (WPX_Font *fp) {
	if (!fp) return;
	for (int s = 0; s < WPX_FONT_CACHE_SLOTS; ++s) {
		if (!fp->slots[s].baked) continue;
		for (int i = 0; i < fp->count; ++i) free(fp->slots[s].baked[i].cov);
		free(fp->slots[s].baked);
	}
	free(fp->verts);
	free(fp->indices);
	free(fp->glyphs);
	free(fp);
}

/* Vector text (smooth scaling) from the TOP-LEFT corner.
   scale = pixels per font unit. */
WINPIXELDLL void WINPIXELCALL wpx_text_font (WPX_Font *font, Color32 color, float scale, int x, int y, const char *fmt, ...) {

	if (!font) return;

	char buf[WPX_FONT_MAX_TEXT] = {0};
	va_list ap;
	va_start(ap, fmt);
	vsnprintf(buf, sizeof(buf), fmt, ap);
	va_end(ap);

	baked_glyph *baked = wpx_font_ensure(font, scale);
	if (!baked) return;
	wpx_font_draw_topleft(font, baked, color, (float)x, (float)y, buf);
}

/* Centered vector text: (x,y) is the CENTER of the block. */
WINPIXELDLL void WINPIXELCALL wpx_text_font_center (WPX_Font *font, Color32 color, float scale, int x, int y, const char *fmt, ...) {

	if (!font) return;

	char buf[WPX_FONT_MAX_TEXT] = {0};
	va_list ap;
	va_start(ap, fmt);
	vsnprintf(buf, sizeof(buf), fmt, ap);
	va_end(ap);

	baked_glyph *baked = wpx_font_ensure(font, scale);
	if (!baked) return;

	float w = 0.0f;
	int top = 0, bot = 0, have = 0;
	for (const unsigned char *p = (const unsigned char *)buf; *p; ++p) {
		int c = *p;
		if (c < font->first || c > font->last) continue;
		const baked_glyph *bg = &baked[c - font->first];
		w += bg->advance;
		if (bg->cov) {
			if (!have || bg->oy        < top) top = bg->oy;
			if (!have || bg->oy + bg->h > bot) bot = bg->oy + bg->h;
			have = 1;
		}
	}

	float tlx = (float)x - w * 0.5f;
	float tly = (float)y - (bot - top) * 0.5f;
	wpx_font_draw_topleft(font, baked, color, tlx, tly, buf);
}
